"use client";
import Link from "next/link";
import {createContext,useContext,useEffect,useRef,useState} from "react";
import {money,products,spritePosition} from "./products";
export type CartItem={slug:string;size:number;quantity:number};
type CartValue={items:CartItem[];add:(slug:string,size:number)=>void;change:(slug:string,size:number,delta:number)=>void;remove:(slug:string,size:number)=>void;clear:()=>void;open:()=>void;total:number;count:number};
const Context=createContext<CartValue|null>(null);
export function useCart(){const value=useContext(Context);if(!value)throw new Error("CartProvider required");return value}
export function CartProvider({children}:{children:React.ReactNode}){const[items,setItems]=useState<CartItem[]>([]);const[drawer,setDrawer]=useState(false);const closeRef=useRef<HTMLButtonElement>(null);const triggerRef=useRef<HTMLButtonElement>(null);const loaded=useRef(false);
useEffect(()=>{const timer=window.setTimeout(()=>{try{const saved=localStorage.getItem("para-cart");if(saved)setItems(JSON.parse(saved))}catch{localStorage.removeItem("para-cart")}loaded.current=true},0);return()=>window.clearTimeout(timer)},[]);useEffect(()=>{if(loaded.current)localStorage.setItem("para-cart",JSON.stringify(items))},[items]);useEffect(()=>{document.body.classList.toggle("shop-drawer-open",drawer);if(drawer)requestAnimationFrame(()=>closeRef.current?.focus());return()=>document.body.classList.remove("shop-drawer-open")},[drawer]);useEffect(()=>{const key=(e:KeyboardEvent)=>e.key==="Escape"&&setDrawer(false);window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
const add=(slug:string,size:number)=>setItems(c=>{const f=c.find(i=>i.slug===slug&&i.size===size);return f?c.map(i=>i===f?{...i,quantity:i.quantity+1}:i):[...c,{slug,size,quantity:1}]});const change=(slug:string,size:number,delta:number)=>setItems(c=>c.map(i=>i.slug===slug&&i.size===size?{...i,quantity:Math.max(1,i.quantity+delta)}:i));const remove=(slug:string,size:number)=>setItems(c=>c.filter(i=>!(i.slug===slug&&i.size===size)));const detailed=items.map(item=>({item,product:products.find(p=>p.slug===item.slug)!}));const total=detailed.reduce((s,{item,product})=>s+item.quantity*product.price,0);const count=items.reduce((s,i)=>s+i.quantity,0);
return <Context.Provider value={{items,add,change,remove,clear:()=>setItems([]),open:()=>setDrawer(true),total,count}}><header className="shop-header"><Link prefetch={false} className="shop-logo" href="/shop">ПАРА<sup>®</sup></Link><nav aria-label="Навигация магазина"><Link prefetch={false} href="/shop#catalog">Каталог</Link><Link prefetch={false} href="/shop#edit">Подборка</Link><Link prefetch={false} href="/">ANESTIS ↗</Link></nav><button ref={triggerRef} className="shop-bag" type="button" onClick={()=>setDrawer(true)} aria-haspopup="dialog">КОРЗИНА <span>{count}</span></button></header>{children}<div className={`cart-scrim ${drawer?"active":""}`} onClick={()=>setDrawer(false)} aria-hidden="true"/><aside className={`cart-drawer ${drawer?"active":""}`} role="dialog" aria-modal="true" aria-label="Корзина" aria-hidden={!drawer}><div className="cart-head"><p>КОРЗИНА / {count}</p><button ref={closeRef} onClick={()=>setDrawer(false)}>ЗАКРЫТЬ ×</button></div>{!items.length?<div className="cart-empty"><b>ПОКА ПУСТО.</b><p>Добавьте пару и выберите размер — мы сохраним выбор на этом устройстве.</p><button onClick={()=>setDrawer(false)}>В КАТАЛОГ ↘</button></div>:<><div className="cart-items">{detailed.map(({item,product})=><article className="cart-item" key={`${item.slug}-${item.size}`}><div className="product-visual cart-visual" style={{backgroundPosition:spritePosition(product.sprite)}}/><div><span>{product.brand}</span><h3>{product.name}</h3><p>РАЗМЕР {item.size}</p><div className="cart-qty"><button onClick={()=>change(item.slug,item.size,-1)}>−</button><b>{item.quantity}</b><button onClick={()=>change(item.slug,item.size,1)}>+</button></div></div><div><b>{money(product.price*item.quantity)}</b><button className="cart-remove" onClick={()=>remove(item.slug,item.size)}>УДАЛИТЬ</button></div></article>)}</div><div className="cart-total"><span>ИТОГО</span><b>{money(total)}</b></div><Link prefetch={false} className="cart-checkout" href="/shop/checkout" onClick={()=>setDrawer(false)}>ОФОРМИТЬ ЗАКАЗ <span>↗</span></Link><p className="cart-demo">ДЕМО-ВИТРИНА / ОПЛАТА НЕ СПИСЫВАЕТСЯ</p></>}</aside></Context.Provider>}
