"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import {useRef} from "react";
import {money,products,productVisualStyle,Product} from "./products";
const groups=[
  {name:"Кроссовки" as const,index:"01",copy:"Городские, беговые и технические силуэты для быстрого темпа."},
  {name:"Туфли" as const,index:"02",copy:"Кожа, выверенная форма и классика без консервативного настроения."},
  {name:"Ботинки" as const,index:"03",copy:"Уверенный протектор и плотные материалы для сложного рельефа."},
];
export default function GroupedCatalog(){return <main className="shop-page"><section className="shop-hero"><div className="shop-track" aria-hidden="true"><span>01</span><span>СЛЕД / ГОРОД / ДВИЖЕНИЕ</span></div><p className="shop-kicker">МУЛЬТИБРЕНДОВАЯ ОБУВНАЯ ВИТРИНА / МОСКВА</p><h1><span>ТВОЯ</span><span>ПАРА.</span></h1><div className="shop-hero-shoe" role="img" aria-label="Чёрные технические кроссовки"/><p className="shop-hero-copy">18 пар для города, офиса, тропы и дней, когда маршрут меняется на ходу.</p><a className="shop-enter" href="#catalog">СМОТРЕТЬ КАТАЛОГ <span>↘</span></a></section><div className="shop-marquee" aria-hidden="true"><div>NEW STEP ✳ HARD GROUND ✳ YOUR PACE ✳ NEW STEP ✳ HARD GROUND ✳ YOUR PACE ✳</div></div><section className="rail-catalog" id="catalog"><header className="rail-catalog-intro"><p>КАТАЛОГ / {products.length} МОДЕЛЕЙ</p><h2>ТРИ<br/>МАРШРУТА.</h2><span>Листайте каждую линию отдельно. Каталог запоминает не категории, а характер движения.</span></header>{groups.map(group=><ProductRail key={group.name} {...group} items={products.filter(product=>product.category===group.name)}/>)}</section><section className="shop-editorial" id="edit"><div><span>ПОДБОРКА / 03</span><h2>ГОРОД<br/>МЕНЯЕТ<br/>РЕЛЬЕФ.</h2></div><div className="editorial-shoe" aria-hidden="true"/><p>Асфальт, лестницы, мокрый камень. Три пары с подошвой, которая не просит сбавлять темп.</p><a href="/shop/ridge-moss">СМОТРЕТЬ RIDGE MOSS ↗</a></section><footer className="shop-footer"><a className="shop-logo" href="/shop">ПАРА<sup>®</sup></a><a href="/">СДЕЛАНО ANESTIS ↗</a></footer></main>}
function ProductRail({name,index,copy,items}:{name:string,index:string,copy:string,items:Product[]}){const railRef=useRef<HTMLDivElement>(null);const move=(direction:number)=>railRef.current?.scrollBy({left:direction*railRef.current.clientWidth*.82,behavior:"smooth"});return <section className="product-rail" aria-labelledby={`rail-${index}`}><header><div><span>{index} / {String(items.length).padStart(2,"0")}</span><h2 id={`rail-${index}`}>{name}</h2></div><p>{copy}</p><div className="rail-controls"><button type="button" onClick={()=>move(-1)} aria-label={`Листать ${name} назад`}>←</button><button type="button" onClick={()=>move(1)} aria-label={`Листать ${name} вперёд`}>→</button></div></header><div className="rail-track" ref={railRef}>{items.map(product=><article className="rail-card" key={product.slug}><a href={`/shop/${product.slug}`} className="rail-image"><div className="product-visual" style={productVisualStyle(product)}/><span>{product.note}</span><i>↗</i></a><div className="rail-meta"><span>{product.brand}</span><h3><a href={`/shop/${product.slug}`}>{product.name}</a></h3><p>{product.color}</p><b>{money(product.price)}</b></div></article>)}</div></section>}
