export type Product = { slug:string; name:string; brand:string; category:"Кроссовки"|"Трейл"|"Классика"; price:number; color:string; sizes:number[]; sprite:number; note:string; description:string };
export const products:Product[]=[
{slug:"vector-black",name:"Vector 09",brand:"NORTH/FORM",category:"Кроссовки",price:18990,color:"Чёрный",sizes:[39,40,41,42,43,44],sprite:0,note:"NEW / TECH",description:"Техническая городская пара с многослойным верхом и амортизирующей подошвой."},
{slug:"relay-cream",name:"Relay 77",brand:"MOTION LAB",category:"Кроссовки",price:15490,color:"Молочный / бордо",sizes:[37,38,39,40,41,42],sprite:1,note:"EDITOR'S PICK",description:"Ретро-силуэт для длинных городских маршрутов. Замша, сетка и цепкий резиновый профиль."},
{slug:"ridge-moss",name:"Ridge Moss",brand:"ALTITUDE",category:"Трейл",price:21990,color:"Хаки",sizes:[40,41,42,43,44,45],sprite:2,note:"TRAIL",description:"Защищённая трейловая модель с быстрым шнурованием и глубоким протектором."},
{slug:"office-01",name:"Office 01",brand:"COMMON FORM",category:"Классика",price:19990,color:"Чёрный",sizes:[39,40,41,42,43,44],sprite:3,note:"CITY",description:"Лоферы с массивной подошвой: строгий верх, уверенная посадка и современная пропорция."},
{slug:"chrome-runner",name:"Chrome Runner",brand:"MOTION LAB",category:"Кроссовки",price:17990,color:"Серебристый",sizes:[36,37,38,39,40,41,42],sprite:4,note:"BESTSELLER",description:"Лёгкая беговая конструкция, переосмысленная для города и ежедневной носки."},
{slug:"blank-court",name:"Blank Court",brand:"COMMON FORM",category:"Кроссовки",price:12990,color:"Белый",sizes:[36,37,38,39,40,41,42,43],sprite:5,note:"ESSENTIAL",description:"Чистая кожаная пара без лишних деталей. Мягкая стелька и спокойный силуэт."},
{slug:"relay-wine",name:"Relay Wine",brand:"NORTH/FORM",category:"Кроссовки",price:16490,color:"Бордо",sizes:[38,39,40,41,42,43],sprite:6,note:"LIMITED",description:"Насыщенная замша, контрастная подошва и спортивная геометрия конца семидесятых."},
{slug:"terrain-black",name:"Terrain 4X",brand:"ALTITUDE",category:"Трейл",price:23490,color:"Чёрный",sizes:[40,41,42,43,44,45],sprite:7,note:"ALL TERRAIN",description:"Устойчивая модель для смешанного рельефа с защищённым носком и агрессивной подошвой."},
{slug:"line-navy",name:"Line Navy",brand:"COMMON FORM",category:"Кроссовки",price:13990,color:"Тёмно-синий",sizes:[37,38,39,40,41,42,43],sprite:8,note:"CITY",description:"Низкий замшевый силуэт с тональной отделкой для спокойных повседневных комплектов."},
{slug:"flux-lime",name:"Flux Lime",brand:"MOTION LAB",category:"Кроссовки",price:19490,color:"Серый / лайм",sizes:[36,37,38,39,40,41,42],sprite:9,note:"DROP 02",description:"Дышащая сетка, упругая пятка и кислотный акцент, который отмечает движение."},
{slug:"field-olive",name:"Field Low",brand:"NORTH/FORM",category:"Кроссовки",price:14990,color:"Оливковый",sizes:[38,39,40,41,42,43,44],sprite:10,note:"SUEDE",description:"Минималистичная замшевая пара с широкой колодкой и мягкой подкладкой."},
{slug:"formal-wine",name:"Formal 02",brand:"COMMON FORM",category:"Классика",price:22490,color:"Тёмный бордо",sizes:[39,40,41,42,43,44,45],sprite:11,note:"LEATHER",description:"Полированные кожаные лоферы на рельефной подошве для строгих и свободных сочетаний."}];
export const money=(value:number)=>new Intl.NumberFormat("ru-RU").format(value)+" ₽";
export const spritePosition=(index:number)=>`${(index%3)*50}% ${Math.floor(index/3)*(100/3)}%`;
