export type Product = { slug:string; name:string; brand:string; category:"Кроссовки"|"Туфли"|"Ботинки"; price:number; color:string; sizes:number[]; sprite:number; sheet?:1|2; note:string; description:string };
export const products:Product[]=[
{slug:"vector-black",name:"Vector 09",brand:"NORTH/FORM",category:"Кроссовки",price:18990,color:"Чёрный",sizes:[39,40,41,42,43,44],sprite:0,note:"NEW / TECH",description:"Техническая городская пара с многослойным верхом и амортизирующей подошвой."},
{slug:"relay-cream",name:"Relay 77",brand:"MOTION LAB",category:"Кроссовки",price:15490,color:"Молочный / бордо",sizes:[37,38,39,40,41,42],sprite:1,note:"EDITOR'S PICK",description:"Ретро-силуэт для длинных городских маршрутов. Замша, сетка и цепкий резиновый профиль."},
{slug:"ridge-moss",name:"Ridge Moss",brand:"ALTITUDE",category:"Ботинки",price:21990,color:"Хаки",sizes:[40,41,42,43,44,45],sprite:2,note:"TRAIL",description:"Защищённая трейловая модель с быстрым шнурованием и глубоким протектором."},
{slug:"office-01",name:"Office 01",brand:"COMMON FORM",category:"Туфли",price:19990,color:"Чёрный",sizes:[39,40,41,42,43,44],sprite:3,note:"CITY",description:"Лоферы с массивной подошвой: строгий верх, уверенная посадка и современная пропорция."},
{slug:"chrome-runner",name:"Chrome Runner",brand:"MOTION LAB",category:"Кроссовки",price:17990,color:"Серебристый",sizes:[36,37,38,39,40,41,42],sprite:4,note:"BESTSELLER",description:"Лёгкая беговая конструкция, переосмысленная для города и ежедневной носки."},
{slug:"blank-court",name:"Blank Court",brand:"COMMON FORM",category:"Кроссовки",price:12990,color:"Белый",sizes:[36,37,38,39,40,41,42,43],sprite:5,note:"ESSENTIAL",description:"Чистая кожаная пара без лишних деталей. Мягкая стелька и спокойный силуэт."},
{slug:"relay-wine",name:"Relay Wine",brand:"NORTH/FORM",category:"Кроссовки",price:16490,color:"Бордо",sizes:[38,39,40,41,42,43],sprite:6,note:"LIMITED",description:"Насыщенная замша, контрастная подошва и спортивная геометрия конца семидесятых."},
{slug:"terrain-black",name:"Terrain 4X",brand:"ALTITUDE",category:"Ботинки",price:23490,color:"Чёрный",sizes:[40,41,42,43,44,45],sprite:7,note:"ALL TERRAIN",description:"Устойчивая модель для смешанного рельефа с защищённым носком и агрессивной подошвой."},
{slug:"line-navy",name:"Line Navy",brand:"COMMON FORM",category:"Кроссовки",price:13990,color:"Тёмно-синий",sizes:[37,38,39,40,41,42,43],sprite:8,note:"CITY",description:"Низкий замшевый силуэт с тональной отделкой для спокойных повседневных комплектов."},
{slug:"flux-lime",name:"Flux Lime",brand:"MOTION LAB",category:"Кроссовки",price:19490,color:"Серый / лайм",sizes:[36,37,38,39,40,41,42],sprite:9,note:"DROP 02",description:"Дышащая сетка, упругая пятка и кислотный акцент, который отмечает движение."},
{slug:"field-olive",name:"Field Low",brand:"NORTH/FORM",category:"Кроссовки",price:14990,color:"Оливковый",sizes:[38,39,40,41,42,43,44],sprite:10,note:"SUEDE",description:"Минималистичная замшевая пара с широкой колодкой и мягкой подкладкой."},
{slug:"formal-wine",name:"Formal 02",brand:"COMMON FORM",category:"Туфли",price:22490,color:"Тёмный бордо",sizes:[39,40,41,42,43,44,45],sprite:11,note:"LEATHER",description:"Полированные кожаные лоферы на рельефной подошве для строгих и свободных сочетаний."},
{slug:"shift-lime",name:"Shift Lime",brand:"MOTION LAB",category:"Кроссовки",price:20990,color:"Графит / лайм",sizes:[37,38,39,40,41,42,43],sprite:0,sheet:2,note:"NEW",description:"Массивная городская пара с мягкой геометрией и точным лаймовым акцентом."},
{slug:"mono-cream",name:"Mono Cream",brand:"COMMON FORM",category:"Кроссовки",price:15990,color:"Кремовый",sizes:[36,37,38,39,40,41,42],sprite:1,sheet:2,note:"CLEAN",description:"Спокойный кожаный силуэт с широкой посадкой и тональной отделкой."},
{slug:"derby-oxblood",name:"Derby 03",brand:"COMMON FORM",category:"Туфли",price:24990,color:"Оксблад",sizes:[39,40,41,42,43,44,45],sprite:2,sheet:2,note:"FORMAL",description:"Классические дерби из полированной кожи с вытянутой современной пропорцией."},
{slug:"chukka-earth",name:"Chukka Earth",brand:"NORTH/FORM",category:"Ботинки",price:23990,color:"Тёмно-коричневый",sizes:[39,40,41,42,43,44,45],sprite:3,sheet:2,note:"SUEDE",description:"Замшевые ботинки на каждый день с мягким верхом и цепкой подошвой."},
{slug:"monk-coffee",name:"Monk 02",brand:"COMMON FORM",category:"Туфли",price:26990,color:"Кофейный",sizes:[39,40,41,42,43,44],sprite:4,sheet:2,note:"BUCKLE",description:"Монки с двумя пряжками, плотной кожей и лаконичным миндалевидным носком."},
{slug:"combat-black",name:"Combat 08",brand:"ALTITUDE",category:"Ботинки",price:27990,color:"Чёрный",sizes:[39,40,41,42,43,44,45],sprite:5,sheet:2,note:"HEAVY",description:"Высокие кожаные ботинки с усиленной шнуровкой и рельефной подошвой."}];
export const money=(value:number)=>new Intl.NumberFormat("ru-RU").format(value)+" ₽";
export const spritePosition=(index:number)=>`${(index%3)*50}% ${Math.floor(index/3)*(100/3)}%`;
export const productVisualStyle=(product:Product)=>({backgroundImage:`url('/images/${product.sheet===2?"para-shoes-02.png":"para-shoes.png"}')`,backgroundSize:product.sheet===2?"300% 200%":"300% 400%",backgroundPosition:product.sheet===2?`${(product.sprite%3)*50}% ${Math.floor(product.sprite/3)*100}%`:spritePosition(product.sprite)});
